set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
bind -n C-l if-shell -F '#{window_zoomed_flag}' 'resize-pane -Z; select-pane -t :.+; resize-pane -Z' 'select-pane -t :.+'


# Vertical split using Ctrl+b then |
bind | split-window -h

# Horizontal split using Ctrl+b then _
bind _ split-window -v


set -g renumber-windows on

bind-key f display-popup -E -w 70% -h 50% "~/.local/bin/tmux-window-fzf"

bind-key -n C-q last-window

# High-contrast border for the active pane
set -g pane-active-border-style fg=brightcyan,bold

# Make the active window stand out (yellow background, black bold text)
set -g window-status-current-style bg=yellow,fg=black,bold

# Add extra spacing/formatting around the active window tag
set -g window-status-current-format " #[fg=black,bg=yellow,bold] #I:#W#F " 
