set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
bind -n C-q select-pane -t :.+


# Split panes inherit current pane directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


set -g renumber-windows on

unbind w
bind-key w display-popup -E -w 70% -h 50% "~/.local/bin/tmux-window-fzf"
