[opener]
zathura = [
    { run = "zathura %s1", orphan = true, for = "unix" }
]
glow = [
    { run = 'glow -p "$1"', block = true, for = "unix" }
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = "zathura" },
    { url = "*.md", use = "glow" }
]
